### PR TITLE
Improve new workspace UX

### PR DESCRIPTION
**Pull request by dabbott**
## What

- Updated ComponentPreviewCard design to match new colors/text styles design
- Updated margins and sizing of ComponentPreviewCollection
- Added a README to the new project template
- Links in markdown open in external browser

This new overview screen is 🔥🔥🔥. Great job @mathieudutour!

The default new project template:

screen shot 2019-01-09 at 1 28 13 pm

My SourceNote workspace:

screen shot 2019-01-09 at 1 09 15 pm

### CODE REVIEW

**Comment by ryngonzalez** [comment]
this is awesomeeeee

**Comment by dabbott** [comment]
Lona is getting good TOO FAST, it's kind of scary

**Comment by mathieudutour** [comment]
I really want to get the documentation part going soon, I feel that's the main point before having something really great!

How do you feel about adding a dmg build to the CI soon?

**Comment by dabbott** [comment]
Documentation will definitely be key for anyone to be able to get started with Lona.

And now for a long answer to a simple question, which probably wasn't what you were looking for:

**Comment by dabbott** [comment]
Re: the dmg, that's really going to open the floodgates of people trying Lona, and I don't think I'm ready for that yet. I don't think Lona is ready as a product either, but it's more that I'm not ready.

I want this to be a **great** open source project with a well-managed repo, a welcoming community, and plenty of resources & support for folks getting started. I think in the long run that's going to be the most important thing, if we're seriously trying to change how people design and code apps. I work on this a lot, but I don't make enough $ for that to be sustainable. I want to have a solid plan in place when we release the dmg (and make a launch announcement) so that I can earn enough $ to keep the project going and make sure the community gets off the ground. I'm not sure if the $ will be from enterprise support plans (i.e. what I'm doing now), egghead-style video tutorials, some kind of paid plugin, or what... but I want to be fully ready when we open the floodgates. I think $ and community are the most likely things to make or break this. I don't want this to be another OSS project where the maintainers are struggling financially. There are other ways things could play out of course, e.g. over the next couple months we might get a bunch of active contributors & maintainers organically, and then I wouldn't need the $ or time to focus on the community and keep the project alive... or there could be one big corporate sponsor that takes care of all the $... but I see those as a much less likely outcomes.

For now I still want to limit the community to people who are serious about adopting Lona. It's still rough enough that even with tons of documentation, it would be quite hard to adopt without support. I want to have the bandwidth to support anyone trying to get started with it at their company. I don't want to set the expectation that it's ready for everyone to use (by providing an app binary) and let people down. There's already so much skepticism around cross-platform solutions (most of it valid) that initial negative reactions could hurt the project tremendously (e.g. React Native, and to some extent Lona, @ Airbnb -- although that's only a small part of the story). So far, asking people to build Lona themselves has been extremely effective at keeping the community small and dedicated. Anyone seriously considering this as a tool for creating & maintaining their design system can easily justify spending the time to build it.

Anyway, the short answer is that I'm not ready to release a dmg. Don't quote me on this, but given the current pace (and the events I expect to unfold in the next month or two), in my head I'm hoping for a dmg/launch around April.

> I know this goes way beyond the question of whether or not we release a dmg soon, but I want to be totally transparent with anyone who contributes their time to the project

**Comment by mathieudutour** [comment]
Makes total sense :+1:

(By the documentation part, I was talking about the documentation of the components, with a storybook or something)

**Comment by dabbott** [comment]
Ooh ok, I thought that's what you meant at first, but then I got distracted by the dmg thing, and forgot and somehow was on the Lona docs track.

Component documentation will be seriously game-changing. I had to build all that manually at Airbnb, and we're just gonna be able to generate it instantly.

**Pull request merged**
