### PR TITLE
disable dark mode for now

### PR DESCRIPTION
**Pull request by mathieudutour**
## What

Disable dark mode on macOS 10.14 for now otherwise half of the controls are white while the others are black

### CODE REVIEW

**Comment by dabbott** [comment]
@mathieudutour are you able to view the build logs?

It looks like this might be failing due to being built on Xcode 9.3. I guess we probably need to update to 10.X to support macOS 10.14?

```
❌  /Users/travis/build/airbnb/Lona/studio/LonaStudio/AppDelegate.swift:18:13: value of type 'NSApplication' has no member 'appearance'
            NSApp.appearance = NSAppearance(named: .aqua)
            ^~~~~ ~~~~~~~~~~
```

And

```
The command "carthage build --platform macOS" exited with 0.
$ xcodebuild -version
Xcode 9.3
Build version 9E145

The command "xcodebuild -version" exited with 0.
$ xcodebuild -showsdks
iOS SDKs:
	iOS 11.3                      	-sdk iphoneos11.3
iOS Simulator SDKs:
	Simulator - iOS 11.3          	-sdk iphonesimulator11.3
macOS SDKs:
	macOS 10.13                   	-sdk macosx10.13
tvOS SDKs:
	tvOS 11.3                     	-sdk appletvos11.3
tvOS Simulator SDKs:
	Simulator - tvOS 11.3         	-sdk appletvsimulator11.3
watchOS SDKs:
	watchOS 4.3                   	-sdk watchos4.3
watchOS Simulator SDKs:
	Simulator - watchOS 4.3       	-sdk watchsimulator4.3
```

**Comment by mathieudutour** [comment]
Ah possibly, I'm indeed on Xcode 10. I thought it would work on Xcode 9 but apparently not.

I have local changes to move to Switch 4.2 and Xcode 10 if you want. But happy to keep it local if you want to keep Xcode 9 for a while

**Comment by mathieudutour** [comment]
It is out of beta as of today I think 😄

**Comment by dabbott** [comment]
Oh nice! You're right. I'll update the Xcode version in a separate PR, then we can merge this one

**Comment by dabbott** [comment]
@mathieudutour can you rebase this? The it'll build in Xcode 10.

**Comment by mathieudutour** [comment]
Done :+1:

**Pull request merged**
