### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by dennislaupman**
## What

Updated documentation

## Why

Sketch would work without this installation

## Major Changes

* I added the modules for this change…
* And this other thing too!

## Requirements for Merging

- [ ] It should do this
- [ ] It should edit this file
- [ ] It should look like this

## Testing Plan

- [ ] Tested this change locally
- [ ] Checked that existing features work

## Feedback

I'm looking for feedback on:

* <this important decision>
* <this design>
* <this code style>

cc: @dabbott, @ryngonzalez

### CODE REVIEW

**Comment by dabbott** [comment]
Honestly I haven't tested this in a while... does the sketch export still work? If it works, we can document it. Otherwise, I probably wouldn't yet.

I think the right solution here is to commit the `node_modules`. Lona Studio should be able to run this script via the GUI, so the `node_modules` will need to be installed already:

screen shot 2017-12-21 at 11 48 36 am

**Comment by dennislaupman** [comment]
Yes after the NPM it works nice!

**Comment by dennislaupman** [comment]
I will commit and create a pull request

**Comment by dennislaupman** [comment]
Hmmmzzz I thing commiting  the node module folder isn't an option ;) 

image

**Comment by ljharb** [comment]
Committing node_modules is never a good idea.

CI and users (or app code) should run `npm install`. If you need determinism, use a lockfile.

**Comment by dennislaupman** [comment]
@ljharb: True ;) That was also my opinion ;-) I'm checking out right now what is the best moment to run the npm -i

**Comment by dabbott** [comment]
I personally don't have any problem with committing node_modules as a super low effort solution, but agree that installing them as part of a hook is a better plan.

Just remember @dennislaupman that we either need to build the node_modules against node 8.4 (the one bundled in Lona) or remove the native dependencies (node-obj-c) entirely.

**Comment by dabbott** [comment]
@dennislaupman I'm going to close this, since it's been open for a while, and the task changed a bit. We should still figure out a good way to make the export-to-sketch command work by automatically installing npm modules at some point -- but we can open a separate issue for it.

**Pull request closed without merging**
