### PR TITLE
Removed Pods folder, workspace and added SwiftLint.

### PR DESCRIPTION
**Pull request by huyphams**
## What

- Refactor Lona project and add coding convention rules

## Why

- Pods folder and workspace can be installed/created via pod install.
- Code quality can be improved by adding SwiftLint.

## Major Changes

- Removed Pods folder.
- Remove Workspace
- Added SwiftLint
- Added SwiftLint rules
- Updated .gitignore

## Testing Plan

- [x] Tested this change locally
- [x] Checked that existing features work

## Feedback

I'm looking for feedback on:

* this important decision.

cc: @dabbott @ryngonzalez, @NghiaTranUIT

### CODE REVIEW

**Comment by dabbott** [comment]
This all seems good :+1:. I haven't used SwiftLint before so I don't know which rules we should have, but I'm sure we can figure that out as we go.

I just merged the PR that adds Travis (seems like a good thing to have before a refactor), but it resulted in some conflicts.

I'm gonna try to resolve the conflicts locally. I think it should be straightforward, but I'll let you know if I run into any issues.

**Comment by dabbott** [comment]
Let me know if this looks OK. I resolved the conflicts and use the local installation of SwiftLint: https://github.com/airbnb/Lona/pull/70

**Comment by huyphams** [comment]
`This all seems good 👍. I haven't used SwiftLint before so I don't know which rules we should have, but I'm sure we can figure that out as we go.` => I added many rules because Lona has violated many rules can't be completed. One this request merged, we can remove some rule and refactor step by step.
@huyphams Let me know if this looks OK. I resolved the conflicts and use the local installation of SwiftLint: #70 => Sure, I'm checking it now.

**Comment by huyphams** [comment]
Update @dabbott looks good to me 👍

**Comment by dabbott** [comment]
Merged as https://github.com/airbnb/Lona/pull/70

**Pull request closed without merging**
