### PR TITLE
allow having common plugins stored in the app support folder

### PR DESCRIPTION
**Pull request by mathieudutour**
## What

The plugins are now sourced from both
- the `/plugins` folder of the current workspace
- the `~/Library/Application Support/${BUNDLE_IDENFIFIER}/plugins` folder

cc: @dabbott

### CODE REVIEW

**Comment by dabbott** [comment]
Tests fail with:

```
Error: No available formula with the name "danger/tap/danger-swift" 
Please tap it and then try again: brew tap danger/tap
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
The command "brew install danger/tap/danger-swift" failed and exited with 1 during .
```

I forget, did we change this recently?

**Comment by dabbott** [comment]
Alright, let's add it and see if we use it.

Any idea on the tests? I sorta remember changing the danger stuff recently

**Comment by mathieudutour** [comment]
I'm not sure, there is def `danger/tap/danger-swift` available for me but homebrew was updated to 2.0 yesterday so it might be something related

**Comment by dabbott** [comment]
Oh interesting, that must be it then. I guess with 2.0 you have to run `tap` before `install`. I'm do that now

**Comment by dabbott** [comment]
CI is fixed, can you rebase this on master?

**Pull request merged**
